Repository wimvelzeboer/fflib-apex-extensions, pull requests merged in 2022-01, with the labels that each got.

#20 Add getIdFieldByStringField()
  docs/domains/sobject.md
  sfdx-source/apex-extensions/main/default/classes/domains/fflib_SObjects2.cls
  sfdx-source/apex-extensions/tests/classes/domains/fflib_SObjects2Test.cls
Labels: enhancement

#21 Remove protected object visibility as this only works with 2GP
  sfdx-source/apex-extensions/main/triggerHandler/objects/fflib_TriggerAction__mdt/fflib_TriggerAction__mdt.object-meta.xml
Labels: bug

#23 Improved method for setting read-only field values
  sfdx-source/apex-extensions/main/default/classes/utils/fflib_MockSObjectUtil.cls
Labels: bug, enhancement

#25 Add fflib_RecordTypeId.cls for getting the recordType Ids
  sfdx-source/apex-extensions/main/default/classes/utils/fflib_MockSObjectUtil.cls
  sfdx-source/apex-extensions/main/default/classes/utils/fflib_RecordTypeId.cls
  sfdx-source/apex-extensions/main/default/classes/utils/fflib_RecordTypeId.cls-meta.xml
Labels: enhancement
